apiVersion: apps/v1
kind: deployment
metadata:
  name: deploy-01
  labels:
    app: nginx
  # annotations:
  #   controller.kubernetes.io/pod-deletion-cost: "10"  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx1.20
