apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    appName: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: pod
metadata:
  name: frontend
  labels:
    appName: frontend
spec:
  containers:
  - name: frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
  env:
  - name: CATALOGUE_HOST
    value: "catalogue1"
  - name: CATALOGUE_PORT
    value: "catalogue2"
  - name: USER_HOST
    value: "catalogue3"
  - name: USER_PORT
    value: "catalogue4"
  - name: CART_HOST
    value: "catalogue5"
  - name: CART_PORT
    value: "catalogue6"
  - name: SHIPPING_HOST
    value: "catalogue7"
  - name: SHIPPING_PORT
    value: "catalogue8"
  - name: PAYMENT_HOST
    value: "catalogue9"
  - name: PAYMENT_PORT
    value: "catalogue0"
